### PR TITLE
Also copy .so files when doing a native-image build

### LINKED ISSUE #308: Certain Native image artifacts are not copied to run image
I am using the builder-jammy-base buildpack with the spring-boot-maven-plugin to build a native image. After some troubleshooting with the Graal team (https://github.com/oracle/graal/issues/8273) it seems that certain required artifacts (jdk_library and jdk_liberary_shim .so files) are not being included in the workspace/ directory of containers using the run image generated by this buildpack. We do see them listed as "produced artifacts" in the build log, however.

## Expected Behavior
The following .so files (in bold) from the log snippet below should be included in the workspace/ directory alongside the native image executable (org.example.App):

INFO]     [creator]     Produced artifacts:
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libawt.so** (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libawt_headless.so** (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libawt_xawt.so** (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libfontmanager.so** (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libfreetype.so** (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libjava.so** (jdk_library_shim)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libjavajpeg.so** (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**libjvm.so** (jdk_library_shim)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/**liblcms.so** (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/org.example.App (executable)

## Current Behavior
The files are not included, the directory in the run container only contains the native executable:
image

## Steps to Reproduce

Repro:
1. Please check out the following project for a small, single-class repro of this error: [reproduce-awt-lib-error-graal](https://github.com/tabiStein/reproduce-awt-lib-error-graal)
2. Run mvn clean install in the root directory of the project to build the jar
3. Run mvn -Pnative package to build the native image, called test/repro-awt-lib-error
4. Read the log output and verify that the jdk library artifacts were produced. Attached is a copy of mine for your convenience: 
[packageOutput.txt](https://github.com/paketo-buildpacks/builder-jammy-base/files/14098062/packageOutput.txt)
5. Run docker run test/repro-awt-lib-error
6. The run fails because the libawt.so file is not in the same directory as the image executable (according to the Graal team: https://github.com/oracle/graal/issues/8273#issuecomment-1916571083)

Environment:
GraalVM version 23.0.2 (as determined by buildpack)
JDK major version: 17
OS: MacOS Sonoma 14.2.1
Architecture: 6-Core Intel Core i9
Maven version: 3.9.6
Docker version: 24.0.7

## Motivations
My company is trying to convert one of our microservices to a native executable, using your buildpack. The service uses the Apache PDDocument class, which relies on the Java awt library. Since the library is not available to the native image at runtime, the executable crashes.

### PR DESCRIPTION
**Pull request by dmikusa**
## Summary

Some applications, when native-image runs, will also generate shared libraries which are required to run the application. These libraries get put next to the generated binary file. This change modifies the buildpack to copy these shared libraries after it copies the binary to the application directory.

In a nutshell, native-image runs, writes binary and shared libs to a cached layer. We then copy files from the cached layer to the application directory (i.e. /workspace) which results in them being available in the application image.

Resolves #308 

## Use Cases

Support native-image builds that require additional JNI libraries, like when using AWT.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

File: native/native_image.go [hunk 1]
```diff
@@ -225,3 +210,42 @@ func (n NativeImage) ProcessArguments(layer libcnb.Layer) ([]string, string, err
...
+}
+
+func copyFile(src string, dst string) error {
+	in, err := os.Open(src)
+	if err != nil {
+		return fmt.Errorf("unable to open %s\n%w", src, err)
+	}
+	defer in.Close()
+
+	return sherpa.CopyFile(in, dst)
```
Comment (anthonydahanne) [inline native/native_image.go:250]: there's no signature of `sherpa.CopyFile` that does the Open + error handling + defer close?

**Review by anthonydahanne — APPROVED** [review]
pretty straightforward.
~~you have examples of native images relying on .so files somewhere? in the samples?~~
oh ok #308

File: native/native_image.go (hunk 1 above)
Comment (dmikusa) [reply native/native_image.go:250]: Unfortunately no. I just added a story for that: https://github.com/paketo-buildpacks/libpak/issues/354
